AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: IoT > Lambda > Slack

Parameters:
  IoTButtonDSN:
    Type: String
    Description: "The device serial number (DSN) of the AWS IoT Button. This can be found on the back of the button. The DSN must match the pattern of 'G030 XXXX XXXX XXXX'."
  CertificateARN:
    Type: String
    Description: "The Amazon Resource Name (ARN) of the existing AWS IoT certificate."
  SlackChannel:
    Type: String
    Description: "The Slack channel you want to post to (eg. #general @john)"
  KMSEncryptedHookUrl:
    Type: String
    Description: "The KMS encrypted Slack incoming WebHook url"

Resources:
  IoTThing:
    Type: "AWS::IoT::Thing"
    Properties:
      AttributePayload:
        Attributes:
          name: "IoTButtonNG41"
          type: "iotbutton"
          dsn: !Sub "${IoTButtonDSN}"
  IoTPolicy:
    Type: "AWS::IoT::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action:
              - "iot:Publish"
            Resource:
              - !Sub "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/iotbutton/${IoTButtonDSN}"
  IoTPolicyPrincipalAttachment:
    Type: "AWS::IoT::PolicyPrincipalAttachment"
    Properties:
      PolicyName: !Ref IoTPolicy
      Principal: !Ref CertificateARN
  IoTThingPrincipalAttachment:
    Type: "AWS::IoT::ThingPrincipalAttachment"
    Properties:
      ThingName: !Ref IoTThing
      Principal: !Ref CertificateARN

  IoTFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Description: >-
        An Amazon SNS trigger that sends CloudWatch alarm notifications to
        Slack.
      Environment:
        Variables:
          slackChannel: !Ref SlackChannel
          kmsEncryptedHookUrl: !Ref KMSEncryptedHookUrl
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource: '*'
      Events:
        IoT:
          Type: IoTRule
          Properties:
            AwsIotSqlVersion: "2015-10-08"
            Sql: !Sub >-
              SELECT * FROM 'iotbutton/${IoTButtonDSN}'
